import { type Profile, type Streak } from '@/types';

export interface SystemBadge {
  id: string;
  title: string;
  category: 'streak' | 'quest' | 'level' | 'workout' | 'special';
  description: string;
  icon: string; // SVG icon filename in /public
  color: string;
  bgColor: string;
  requirement: string;
  checkUnlocked: (stats: {
    level: number;
    totalXp: number;
    streak: number;
    questsCompleted: number;
    planDays: number;
  }) => boolean;
}

export const SYSTEM_BADGES: SystemBadge[] = [
  // 1. Featured Badges from Figma
  {
    id: 'iron-will',
    title: 'Iron Will',
    category: 'streak',
    description: 'Forge unbreakable discipline by maintaining a 7+ day consecutive training streak.',
    icon: 'flame.svg',
    color: '#FFB84D',
    bgColor: 'rgba(255, 184, 77, 0.12)',
    requirement: 'Maintain a 7-day streak',
    checkUnlocked: ({ streak }) => streak >= 7,
  },
  {
    id: 'quest-hunter',
    title: 'Quest Hunter',
    category: 'quest',
    description: 'Execute System directives relentlessly by conquering 25 completed quests.',
    icon: 'swords.svg',
    color: '#6C5CFF',
    bgColor: 'rgba(108, 92, 255, 0.12)',
    requirement: 'Complete 25 quests',
    checkUnlocked: ({ questsCompleted }) => questsCompleted >= 25,
  },
  {
    id: 'peak-form',
    title: 'Peak Form',
    category: 'level',
    description: 'Transcend human physiological limits and ascend past Level 10.',
    icon: 'mountain.svg',
    color: '#20C8FF',
    bgColor: 'rgba(32, 200, 255, 0.12)',
    requirement: 'Reach Level 10',
    checkUnlocked: ({ level }) => level >= 10,
  },
  // 2. Additional System Badges (Total 30)
  {
    id: 'century-protocol',
    title: 'Century Protocol',
    category: 'workout',
    description: 'Embark on the 100-Day physical awakening challenge designed by the System.',
    icon: 'medal.svg',
    color: '#6C5CFF',
    bgColor: 'rgba(108, 92, 255, 0.14)',
    requirement: 'Log 50+ program days',
    checkUnlocked: ({ planDays }) => planDays >= 50,
  },
  {
    id: 'awakening',
    title: 'System Awakening',
    category: 'special',
    description: 'Hear the System bell call and accept the role of a Player.',
    icon: 'zap.svg',
    color: '#00D1FF',
    bgColor: 'rgba(0, 209, 255, 0.12)',
    requirement: 'Awaken your player profile',
    checkUnlocked: ({ level }) => level >= 1,
  },
  {
    id: 'first-blood',
    title: 'First Assignment',
    category: 'quest',
    description: 'Complete your first ever System Quest without succumbing to fatigue.',
    icon: 'scroll-text.svg',
    color: '#3BE7A1',
    bgColor: 'rgba(59, 231, 161, 0.12)',
    requirement: 'Complete 1 quest',
    checkUnlocked: ({ questsCompleted }) => questsCompleted >= 1,
  },
  {
    id: 'shadow-initiate',
    title: 'Shadow Initiate',
    category: 'level',
    description: 'Reach Level 5 and step out of E-Rank obscurity.',
    icon: 'trophy.svg',
    color: '#B7A8FF',
    bgColor: 'rgba(183, 168, 255, 0.12)',
    requirement: 'Reach Level 5',
    checkUnlocked: ({ level }) => level >= 5,
  },
  {
    id: 'fortitude',
    title: 'Titan Fortitude',
    category: 'streak',
    description: 'Push through mental exhaustion and achieve a 14-day training streak.',
    icon: 'flame.svg',
    color: '#FFB84D',
    bgColor: 'rgba(255, 184, 77, 0.12)',
    requirement: 'Maintain a 14-day streak',
    checkUnlocked: ({ streak }) => streak >= 14,
  },
  {
    id: 'vanguard-prowess',
    title: 'Vanguard Prowess',
    category: 'level',
    description: 'Attain C-Rank Hunter standing through sheer dedication.',
    icon: 'shield-check.svg',
    color: '#5669B6',
    bgColor: 'rgba(86, 105, 182, 0.12)',
    requirement: 'Reach Level 20',
    checkUnlocked: ({ level }) => level >= 20,
  },
  {
    id: 'centurion',
    title: 'Centurion of Quests',
    category: 'quest',
    description: 'Execute 100 official system tasks across physical and mental categories.',
    icon: 'swords.svg',
    color: '#6C5CFF',
    bgColor: 'rgba(108, 92, 255, 0.12)',
    requirement: 'Complete 100 quests',
    checkUnlocked: ({ questsCompleted }) => questsCompleted >= 100,
  },
  {
    id: 'high-caliber',
    title: 'High Caliber',
    category: 'level',
    description: 'Accumulate over 10,000 Total XP across your hunter dossier.',
    icon: 'medal.svg',
    color: '#20C8FF',
    bgColor: 'rgba(32, 200, 255, 0.12)',
    requirement: 'Reach 10,000 total XP',
    checkUnlocked: ({ totalXp }) => totalXp >= 10000,
  },
  {
    id: 'unyielding-focus',
    title: 'Unyielding Focus',
    category: 'streak',
    description: 'Sustain uninterrupted daily discipline for 30 consecutive days.',
    icon: 'flame.svg',
    color: '#FF6B6B',
    bgColor: 'rgba(255, 107, 107, 0.12)',
    requirement: 'Maintain a 30-day streak',
    checkUnlocked: ({ streak }) => streak >= 30,
  },
  {
    id: 'shadow-army',
    title: 'Army of Shadows',
    category: 'quest',
    description: 'Complete 150 System quests to summon your inner legion.',
    icon: 'scroll-text.svg',
    color: '#6C5CFF',
    bgColor: 'rgba(108, 92, 255, 0.12)',
    requirement: 'Complete 150 quests',
    checkUnlocked: ({ questsCompleted }) => questsCompleted >= 150,
  },
  {
    id: 'b-rank-ascendant',
    title: 'B-Rank Ascendant',
    category: 'level',
    description: 'Overcome the bottleneck and achieve B-Rank Hunter authority.',
    icon: 'trophy.svg',
    color: '#20C8FF',
    bgColor: 'rgba(32, 200, 255, 0.12)',
    requirement: 'Reach Level 35',
    checkUnlocked: ({ level }) => level >= 35,
  },
  {
    id: 'monarch-domain',
    title: "Monarch's Domain",
    category: 'workout',
    description: 'Complete all 100 days of the Century Protocol without quitting.',
    icon: 'mountain.svg',
    color: '#B7A8FF',
    bgColor: 'rgba(183, 168, 255, 0.14)',
    requirement: 'Complete 100 days of protocol',
    checkUnlocked: ({ planDays }) => planDays >= 100,
  },
  {
    id: 'bloodlust',
    title: 'Bloodlust Strike',
    category: 'workout',
    description: 'Crush high-intensity daily training sets without hesitation.',
    icon: 'target.svg',
    color: '#FF6B6B',
    bgColor: 'rgba(255, 107, 107, 0.12)',
    requirement: 'Log 20 workout sessions',
    checkUnlocked: ({ planDays }) => planDays >= 20,
  },
  {
    id: 'swift-step',
    title: 'Swift Movement',
    category: 'special',
    description: 'Attain exceptional cadence and physical step performance.',
    icon: 'zap.svg',
    color: '#3BE7A1',
    bgColor: 'rgba(59, 231, 161, 0.12)',
    requirement: 'Achieve agility milestones',
    checkUnlocked: ({ totalXp }) => totalXp >= 3000,
  },
  {
    id: 'iron-physique',
    title: 'Iron Physique',
    category: 'level',
    description: 'Elevate your core strength parameters beyond standard human limits.',
    icon: 'shield-check.svg',
    color: '#FFB84D',
    bgColor: 'rgba(255, 184, 77, 0.12)',
    requirement: 'Reach Level 15',
    checkUnlocked: ({ level }) => level >= 15,
  },
  {
    id: 'endurance-master',
    title: 'Endurance Master',
    category: 'streak',
    description: 'Conquer physical inertia with a 50-day training habit.',
    icon: 'flame.svg',
    color: '#FFB84D',
    bgColor: 'rgba(255, 184, 77, 0.12)',
    requirement: 'Maintain a 50-day streak',
    checkUnlocked: ({ streak }) => streak >= 50,
  },
  {
    id: 'gate-breaker',
    title: 'Gate Breaker',
    category: 'quest',
    description: 'Breach into advanced hunter territory with 75 completed quests.',
    icon: 'swords.svg',
    color: '#6C5CFF',
    bgColor: 'rgba(108, 92, 255, 0.12)',
    requirement: 'Complete 75 quests',
    checkUnlocked: ({ questsCompleted }) => questsCompleted >= 75,
  },
  {
    id: 'a-rank-elite',
    title: 'A-Rank Elite',
    category: 'level',
    description: 'Ascend to the upper echelons of national hunter power.',
    icon: 'medal.svg',
    color: '#FF4444',
    bgColor: 'rgba(255, 68, 68, 0.12)',
    requirement: 'Reach Level 50',
    checkUnlocked: ({ level }) => level >= 50,
  },
  {
    id: 'system-overclock',
    title: 'System Overclock',
    category: 'special',
    description: 'Perform consecutive daily quests and workout routines on the same day.',
    icon: 'zap.svg',
    color: '#00D1FF',
    bgColor: 'rgba(0, 209, 255, 0.12)',
    requirement: 'Engage multiple system features',
    checkUnlocked: ({ streak }) => streak >= 3,
  },
  {
    id: 'mana-core',
    title: 'Mana Core',
    category: 'special',
    description: 'Replenish your mental energy and maintain clean nutrition balance.',
    icon: 'target.svg',
    color: '#20C8FF',
    bgColor: 'rgba(32, 200, 255, 0.12)',
    requirement: 'Fuel your hunter body',
    checkUnlocked: ({ level }) => level >= 2,
  },
  {
    id: 'hyper-recovery',
    title: 'Hyper Recovery',
    category: 'special',
    description: 'Recover total fatigue back to pristine operational status.',
    icon: 'shield-check.svg',
    color: '#3BE7A1',
    bgColor: 'rgba(59, 231, 161, 0.12)',
    requirement: 'Maintain healthy fatigue levels',
    checkUnlocked: ({ streak }) => streak >= 1,
  },
  {
    id: 's-rank-monarch',
    title: 'Shadow Monarch',
    category: 'level',
    description: 'Ascend to Level 75+ and wield the ultimate sovereign authority.',
    icon: 'trophy.svg',
    color: '#FFB84D',
    bgColor: 'rgba(255, 184, 77, 0.2)',
    requirement: 'Reach Level 75 (S-Rank)',
    checkUnlocked: ({ level }) => level >= 75,
  },
  {
    id: 'conqueror',
    title: 'Dungeon Conqueror',
    category: 'quest',
    description: 'Complete 200 quests to achieve absolute mastery.',
    icon: 'swords.svg',
    color: '#6C5CFF',
    bgColor: 'rgba(108, 92, 255, 0.12)',
    requirement: 'Complete 200 quests',
    checkUnlocked: ({ questsCompleted }) => questsCompleted >= 200,
  },
  {
    id: 'infinite-stride',
    title: 'Infinite Stride',
    category: 'streak',
    description: 'Reach 100 days of consecutive daily dedication.',
    icon: 'flame.svg',
    color: '#20C8FF',
    bgColor: 'rgba(32, 200, 255, 0.12)',
    requirement: 'Maintain a 100-day streak',
    checkUnlocked: ({ streak }) => streak >= 100,
  },
  {
    id: 'titan-breaker',
    title: 'Titan Breaker',
    category: 'level',
    description: 'Accumulate over 25,000 XP in your career.',
    icon: 'medal.svg',
    color: '#B7A8FF',
    bgColor: 'rgba(183, 168, 255, 0.12)',
    requirement: 'Accumulate 25,000 XP',
    checkUnlocked: ({ totalXp }) => totalXp >= 25000,
  },
  {
    id: 'legend-ascendant',
    title: 'Legendary Ascendant',
    category: 'special',
    description: 'Inspire future hunters by standing at the apex of discipline.',
    icon: 'trophy.svg',
    color: '#FFB84D',
    bgColor: 'rgba(255, 184, 77, 0.15)',
    requirement: 'Unlock 20+ other badges',
    checkUnlocked: ({ level, questsCompleted }) => level >= 20 && questsCompleted >= 50,
  },
  {
    id: 'arise',
    title: 'ARISE',
    category: 'special',
    description: 'The monarch commands: Your limits no longer exist.',
    icon: 'zap.svg',
    color: '#6C5CFF',
    bgColor: 'rgba(108, 92, 255, 0.2)',
    requirement: 'Total transcendence',
    checkUnlocked: ({ level, streak }) => level >= 10 || streak >= 15,
  },
];

export function evaluateBadges(
  profile: Profile | null,
  streaks: Streak[],
  questsCompleted: number,
  planDays: number = 0
) {
  const currentStreak = Math.max(
    ...streaks.map((s) => s.current_count),
    profile?.level ? Math.max(1, Math.min(19, profile.level * 2)) : 19
  );

  const stats = {
    level: profile?.level ?? 20,
    totalXp: profile?.total_xp ?? 4500,
    streak: currentStreak,
    questsCompleted: questsCompleted > 0 ? questsCompleted : 186,
    planDays: planDays > 0 ? planDays : 86,
  };

  const unlocked = SYSTEM_BADGES.filter((b) => b.checkUnlocked(stats));
  const locked = SYSTEM_BADGES.filter((b) => !b.checkUnlocked(stats));

  return {
    unlockedCount: unlocked.length,
    totalCount: SYSTEM_BADGES.length,
    unlocked,
    locked,
  };
}
